### PR TITLE
Update translations.js

### PR DESCRIPTION
**Pull request by LILITHLOVEGOOD**
-_-

### CODE REVIEW

**Comment by jQueryBase64MyAss** [comment]
ty

**Comment by jQueryBase64MyAss** [comment]
broken dutch

**Comment by legacy3** [comment]
i loke this broken german copy

**Comment by LILITHLOVEGOOD** [comment]
i feel like a real dev xoxo

**Comment by legacy3** [comment]
luna lovegood!

**Comment by LILITHLOVEGOOD** [comment]
you love her aswell?

**Comment by legacy3** [comment]
she is by far the hottest actor in hp :sisi3:

**Comment by LILITHLOVEGOOD** [comment]
also, http://prntscr.com/9thr0m

**Comment by jQueryBase64MyAss** [comment]
idc

**Comment by legacy3** [comment]
xD

**Comment by LILITHLOVEGOOD** [comment]
how do i disable the email spam :/

**Comment by LILITHLOVEGOOD** [comment]
nvm i found it tyvm guys

**Pull request merged**
