### PR TITLE
Update translations.js

### PR DESCRIPTION
**Pull request by Taunty**
Some sentences were from some useless translators, I changed them by my own language. Thanks!

### CODE REVIEW

**Comment by legacy3** [comment]
hey there, you could add fr-BE and fr-FR

**Comment by jQueryBase64MyAss** [comment]
@LILITHLOVEGOOD @PORNCORE :-1:

**Comment by Taunty** [comment]
@legacy3 Dutch you mean ? Otherwise fr-BE should be the same as fr-FR since we use the same words :p

**Comment by jQueryBase64MyAss** [comment]
@Taunty No need to add a Dutch thing here

**Comment by Taunty** [comment]
@jQueryBase64MyAss Yeah sure, now I don't know how to rename "fr" to "fr-FR" :/

**Comment by LILITHLOVEGOOD** [comment]
@jQueryBase64MyAss dunno staat nog steeds vol met fouten

**Pull request closed without merging**
